### ISSUE TITLE
[object object]

### ISSUE THREAD

**Issue by DevFranciscoCruz** [barbarbar338/locale-parser#1]
Hello I dont know if this is your bug but if not you can help me, im using this package for discord.js and if i use embed.addField(`**${i + 1}**. ${member.username}`, `**Nível**: ${res[i].nivel} - **XP**: ${res[i].xp}`);
member.username, res[i].nivel and res[i].xp work but if i try to put with locale parser return [object object] im getting this values form database with no problem but i cant use with locale parser.
I try to use with locale parser like this 
embed.addField(`${bot.language.get(guildsettings.guildLanguage, "commands", "TopLevel_Field"), { i: i + 1, member: member.user.username }}`, `${bot.language.get(guildsettings.guildLanguage, "commands", "TopLevel_Field2"), { nivel: res[i].nivel, xp: res[i].xp }}`)
If you can help me you can contact me in github or Discord MrPerfectShot#2252

**Comment by barbarbar338** [comment]
Can I see the code and language files you use?

**Comment by DevFranciscoCruz** [comment]
bot.Database.Users.find({
        guildID: message.guild.id
    }).sort([
        ['nível', 'descending']
    ]).exec((err, res) => {
        if (err) console.log(err);
        let i = 0;
        let embed = new Discord.MessageEmbed()
            .setTitle(`${bot.language.get(guildsettings.guildLanguage, "commands", "TopLevel_Title")}`)
            .setDescription(`${bot.language.get(guildsettings.guildLanguage, "commands", "TopLevel_Description")}`)
            .setThumbnail(bot.user.avatarURL)
            .setFooter(bot.language.get(guildsettings.guildLanguage, "commands", "Command_Footer", { commandname: firstUpperCase(this.info.name), botname: bot.user.username }), `${bot.user.avatarURL({ dynamic: true, size: 4096 })}`)
            .setTimestamp()
        if (res.length === 0) {
            embed.setColor(bot.colors.error);
            embed.addField(`${bot.language.get(guildsettings.guildLanguage, "commands", "TopLevel_No_Data_Field")}`, `${bot.language.get(guildsettings.guildLanguage, "commands", "TopLevel_No_Data_Field2")}`)
        } else if (res.length < 10) {
            embed.setColor(bot.colors.success);
            for (i = 0; i < res.length; i++) {
                let member = bot.users.cache.get(res[i].userID)
                if (member) {
                    embed.addField(`${bot.language.get(guildsettings.guildLanguage, "commands", "TopLevel_Field"), { i: i + 1, member: member.username }}`, `${bot.language.get(guildsettings.guildLanguage, "commands", "TopLevel_Field2"), { nivel: res[i].nivel, xp: res[i].xp }}`)
                } else {
                    embed.addField(`${bot.language.get(guildsettings.guildLanguage, "commands", "TopLevel_Field"), { i: i + 1, member: member.username }}`, `${bot.language.get(guildsettings.guildLanguage, "commands", "TopLevel_Field2"), { nivel: res[i].nivel, xp: res[i].xp }}`)
                }
            }
        } else {
            embed.setColor(bot.colors.success);
            for (i = 0; i < 10; i++) {
                let member = bot.users.cache.get(res[i].userID)
                embed.addField(`${bot.language.get(guildsettings.guildLanguage, "commands", "TopLevel_Field"), { i: i + 1, member: member.username }}`, `${bot.language.get(guildsettings.guildLanguage, "commands", "TopLevel_Field2"), { nivel: res[i].nivel, xp: res[i].xp }}`)
            }
        }
        message.channel.send(embed).then(msg => msg.delete({ timeout: bot.guildSettings.get(message.guild.id).guildLimparComandoTempo, reason: bot.guildSettings.get(message.guild.id).guildLimparComandoMSG }))
    }) - Command

TopMoney_Field: "**%{i}**. %{member}"
TopMoney_Field2: "**%{coinsname}**: %{coins}" - Commands.yaml

![screenshot 177](https://user-images.githubusercontent.com/56578626/96990881-9a30f000-151f-11eb-88d3-e66b656db337.jpg)

**Comment by barbarbar338** [comment]
i think it's because of this
```js
`${bot.language.get(guildsettings.guildLanguage, "commands", "TopLevel_Field2"), { nivel: res[i].nivel, xp: res[i].xp }}`
```
Change this to 
```js
`${bot.language.get(guildsettings.guildLanguage, "commands", "TopLevel_Field2", { nivel: res[i].nivel, xp: res[i].xp })}`
```
and don't forget to check your other codes
