### ISSUE TITLE
Using Array

### ISSUE THREAD

**Issue by DevFranciscoCruz** [barbarbar338/locale-parser#2]
Hello I can I Use An Array?
Like i have an array of replies ` let replies = [`${bot.language.get(guildsettings.guildLanguage, "commands", "Drinks_List")}`];`
And a Result:
`let result = Math.floor((Math.random() * replies.length));`
And I want translate the elements of array

`Drinks_List: [{'Whisky', 'Coktail', 'Tequila', 'Cerveja', 'Vodka', 'Vinho', 'Champanhe', 'Rum', 'Licor Beirão', 'Gin', 'Absinto'}]`

I try all or i get a letter or i get [object object]

**Comment by barbarbar338** [comment]
I don't understand what exactly you want to do.

**Comment by DevFranciscoCruz** [comment]
Like i want To get one drink randomly from that list but some drinks need to be translated so i need to use locale-parser

**Comment by barbarbar338** [comment]
you can create a section called `drinks.yaml`
```
📂 locales/
├─── 📝 constants.yaml
├─── 📂 en
│    └───  📝 drinks.yaml
└─── 📂 tr
     └───  📝 drinks.yaml
```
and you can put the following data in it
```
en/drinks.yaml

whisky: Whisky 
cocktail: Cocktail
tequila: Tequila
...

-----------------

tr/drinks.yaml

whisky: Viski
cocktail: Kokteyl
tequila: Tekila
...
```
Then create an array like this and get a random drink from it like this
```js
const drinks = [ "whisky", "cocktail", "tequila", ... ];
const drink = drinks[Math.floor(Math.random() * drinks.length)];
const translatedEn = i18n.get("en", "drinks", drink); // Random drink from en/drinks.yaml
const translatedTr = i18n.get("tr", "drinks", drink); // Random drink from tr/drinks.yaml
```

**Comment by DevFranciscoCruz** [comment]
Oh Thanks A Lot
