### ISSUE TITLE
Typedef error

### ISSUE THREAD

**Issue by bckd00r** [barbarbar338/locale-parser#7]
When I try to install the module I get an error and typedef was deleted from "https://unpkg.com/locale-parser@1.1.0/dist/src/index.d.ts"? 
hope to be fixed soon

**Comment by barbarbar338** [comment]
ı'll fix it asap

**Comment by barbarbar338** [comment]
fixed with v1.1.2 (https://unpkg.com/locale-parser@1.1.2/dist/src/index.d.ts)
